"use client";

import { useState } from "react";
import { generatePolicyBrief, type PolicyBrief } from "@/lib/api";

function download(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function briefToHtml(b: PolicyBrief): string {
  const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const li = (arr: string[]) => arr.map((x) => `<li>${esc(x)}</li>`).join("");
  const qa = b.qa.map((q) => `<div class="qa"><p class="q">Q: ${esc(q.question)}</p><p>${esc(q.answer)}</p></div>`).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(b.title)}</title>
<style>
 body{font-family:Georgia,'Times New Roman',serif;max-width:820px;margin:40px auto;padding:0 24px;color:#1e293b;line-height:1.5}
 h1{font-size:26px;margin-bottom:4px;color:#0f172a}
 .meta{color:#64748b;font-style:italic;margin-bottom:24px}
 h2{font-size:18px;border-bottom:2px solid #e2e8f0;padding-bottom:4px;margin-top:28px;color:#0f766e}
 ol,ul{padding-left:22px} li{margin:6px 0}
 .qa{margin:12px 0} .q{font-weight:bold;margin-bottom:2px}
 footer{margin-top:36px;color:#94a3b8;font-size:12px;border-top:1px solid #e2e8f0;padding-top:12px}
</style></head><body>
<h1>${esc(b.title)}</h1>
<p class="meta">Audience: ${esc(b.audience)} · Generated: ${esc(b.generated_at)}</p>
<h2>Executive summary</h2><p>${esc(b.summary)}</p>
<h2>Key findings</h2><ul>${li(b.key_findings)}</ul>
<h2>Recommendations</h2><ol>${li(b.recommendations)}</ol>
${b.qa.length ? `<h2>Questions &amp; answers</h2>${qa}` : ""}
<footer>Generated by the African Intelligence Cloud — LSMS &amp; Microdata Analytics Engine. Figures are aggregated; no respondent-level data is disclosed.</footer>
</body></html>`;
}

function printBrief(b: PolicyBrief) {
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(briefToHtml(b));
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 300);
}

export interface AIPolicyBriefPanelProps {
  jobId: string;
  defaultTitle?: string;
}

/** Generates a policy brief from a completed analysis job, with an editable
 *  question list and Markdown / HTML / PDF download options. */
export default function AIPolicyBriefPanel({ jobId, defaultTitle }: AIPolicyBriefPanelProps) {
  const [audience, setAudience] = useState("policymakers");
  const [title, setTitle] = useState(defaultTitle || "");
  const [questionsText, setQuestionsText] = useState(
    "Which areas should be prioritised?\nWhat is the overall result?\nWhat does this mean for policy?",
  );
  const [brief, setBrief] = useState<PolicyBrief | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleGenerate() {
    setLoading(true);
    setError(null);
    try {
      const questions = questionsText.split("\n").map((q) => q.trim()).filter(Boolean);
      const b = await generatePolicyBrief({
        job_id: jobId,
        title: title || undefined,
        audience,
        questions: questions.length ? questions : undefined,
      });
      setBrief(b);
    } catch (e: unknown) {
      const msg = (e as { response?: { data?: { detail?: string } } })?.response?.data?.detail;
      setError(msg || "Could not generate the policy brief.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="rounded-xl border border-slate-200 bg-white p-5">
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-lg font-semibold text-aic-dark">AI Policy Brief</h3>
        <span className="text-xs text-slate-400">Generated from this analysis</span>
      </div>

      <div className="grid gap-3 sm:grid-cols-2">
        <div>
          <label className="block text-xs font-semibold text-slate-500 mb-1">Title (optional)</label>
          <input value={title} onChange={(e) => setTitle(e.target.value)}
            placeholder="Auto-generated if blank"
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" />
        </div>
        <div>
          <label className="block text-xs font-semibold text-slate-500 mb-1">Audience</label>
          <input value={audience} onChange={(e) => setAudience(e.target.value)}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" />
        </div>
      </div>

      <div className="mt-3">
        <label className="block text-xs font-semibold text-slate-500 mb-1">Questions (one per line — answered from the analysis)</label>
        <textarea value={questionsText} onChange={(e) => setQuestionsText(e.target.value)} rows={3}
          className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm font-mono" />
      </div>

      {error && <div className="mt-3 rounded-lg bg-red-50 border border-red-200 text-red-700 px-3 py-2 text-sm">{error}</div>}

      <div className="mt-3 flex flex-wrap gap-2">
        <button onClick={handleGenerate} disabled={loading}
          className="btn-primary !py-2 !px-4 text-sm disabled:opacity-60">
          {loading ? "Generating…" : brief ? "Regenerate" : "Generate Policy Brief"}
        </button>
        {brief && (
          <>
            <button onClick={() => download(`${brief.title.replace(/\s+/g, "_")}.md`, brief.markdown, "text/markdown")}
              className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium text-aic-dark hover:bg-slate-50">
              Download Markdown
            </button>
            <button onClick={() => download(`${brief.title.replace(/\s+/g, "_")}.html`, briefToHtml(brief), "text/html")}
              className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium text-aic-dark hover:bg-slate-50">
              Download HTML
            </button>
            <button onClick={() => printBrief(brief)}
              className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium text-aic-dark hover:bg-slate-50">
              Print / Save PDF
            </button>
          </>
        )}
      </div>

      {brief && (
        <article className="mt-6 space-y-5">
          <div>
            <h4 className="text-xl font-bold text-aic-dark">{brief.title}</h4>
            <p className="text-xs text-slate-400 italic">Audience: {brief.audience} · {brief.generated_at}</p>
          </div>
          <section>
            <h5 className="text-sm font-semibold uppercase tracking-wide text-aic-primary mb-1">Executive summary</h5>
            <p className="text-sm text-slate-700 leading-relaxed">{brief.summary}</p>
          </section>
          <section>
            <h5 className="text-sm font-semibold uppercase tracking-wide text-aic-primary mb-1">Key findings</h5>
            <ul className="list-disc pl-5 space-y-1 text-sm text-slate-700">
              {brief.key_findings.map((f, i) => <li key={i}>{f}</li>)}
            </ul>
          </section>
          <section>
            <h5 className="text-sm font-semibold uppercase tracking-wide text-aic-primary mb-1">Recommendations</h5>
            <ol className="list-decimal pl-5 space-y-1 text-sm text-slate-700">
              {brief.recommendations.map((r, i) => <li key={i}>{r}</li>)}
            </ol>
          </section>
          {brief.qa.length > 0 && (
            <section>
              <h5 className="text-sm font-semibold uppercase tracking-wide text-aic-primary mb-2">Questions &amp; answers</h5>
              <div className="space-y-3">
                {brief.qa.map((qa, i) => (
                  <div key={i} className="rounded-lg bg-slate-50 border border-slate-200 p-3">
                    <p className="text-sm font-semibold text-aic-dark">Q: {qa.question}</p>
                    <p className="text-sm text-slate-700 mt-1">{qa.answer}</p>
                  </div>
                ))}
              </div>
            </section>
          )}
        </article>
      )}
    </div>
  );
}
