"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {cleanIntelligence,fetchMicrodataDatasets,planIntelligence,runIntelligenceAnalysis,type AnalysisResultResponse,type IntelligencePlan,type MicrodataDataset} from "@/lib/api";

type Stage="data"|"question"|"plan"|"execute"|"results";
type Purpose="association"|"prediction"|"causal";
const STEPS:[Stage,string][]=[["data","Data"],["question","Question"],["plan","Plan"],["execute","Execute"],["results","Results"]];
const NAV=[["Dashboard","/dashboard","▦"],["Analysis Lab","/analysis-lab","♙"],["Microdata","/microdata","▤"],["Spatial","/microdata/spatial","◫"],["Forecasting","/forecasting","↗"],["AI Research","/research","✣"],["Projects","/projects","▣"]];

export default function Page(){
 const[stage,setStage]=useState<Stage>("data"),[datasets,setDatasets]=useState<MicrodataDataset[]>([]),[datasetId,setDatasetId]=useState(""),[question,setQuestion]=useState("Estimate the effect of rainfall variability, fertiliser use and access to credit on household agricultural productivity."),[outcome,setOutcome]=useState(""),[purpose,setPurpose]=useState<Purpose>("association"),[plan,setPlan]=useState<IntelligencePlan|null>(null),[params,setParams]=useState<Record<string,string>>({}),[approved,setApproved]=useState(false),[result,setResult]=useState<AnalysisResultResponse|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{fetchMicrodataDatasets(0,500).then(r=>{setDatasets(r.items);if(r.items[0])setDatasetId(r.items[0].id)}).catch(()=>setError("Sign in to load the datasets already integrated into the analysis database.")).finally(()=>setLoading(false))},[]);
 const selected=useMemo(()=>datasets.find(d=>d.id===datasetId),[datasets,datasetId]),index=STEPS.findIndex(s=>s[0]===stage);
 async function makePlan(){if(!datasetId||!question.trim()){setError("Select a dataset and enter a research question.");return}setBusy(true);setError("");try{const p=await planIntelligence(datasetId,question.trim());setPlan(p);const v=Object.fromEntries(Object.entries(p.parameters||{}).map(([k,x])=>[k,x==null?"":String(x)]));if(outcome&&!v.welfare_variable)v.welfare_variable=outcome;setParams(v);setStage("plan")}catch{setError("AIC could not build a defensible plan. Check the dataset mapping or rephrase the question.")}finally{setBusy(false)}}
 async function run(){if(!plan||!approved)return;setBusy(true);setStage("execute");setError("");try{let id=datasetId;if(plan.cleaning_steps.length)id=(await cleanIntelligence(id,plan.cleaning_steps)).cleaned_dataset_id;const p=Object.fromEntries(Object.entries(params).filter(([,v])=>v!=="").map(([k,v])=>[k,k==="poverty_line"?Number(v):v]));const r=await runIntelligenceAnalysis(plan.endpoint,id,p);if(r.status==="failed")throw new Error(r.error_message||"Analysis failed");setResult(r);setStage("results")}catch(e){setError(e instanceof Error?e.message:"Analysis failed");setStage("plan")}finally{setBusy(false)}}
 function download(){const u=URL.createObjectURL(new Blob([JSON.stringify({dataset_id:datasetId,question,purpose,plan,params,result},null,2)],{type:"application/json"})),a=document.createElement("a");a.href=u;a.download="aic-analysis-record.json";a.click();URL.revokeObjectURL(u)}
 return <main className="min-h-screen bg-slate-100 p-3 sm:p-6"><div className="mx-auto flex min-h-[740px] max-w-6xl overflow-hidden rounded-2xl border bg-white shadow-sm">
  <aside className="hidden w-56 shrink-0 bg-blue-500 p-5 text-white md:block"><Link href="/" className="flex items-center gap-3 font-bold"><span className="grid h-9 w-9 place-items-center rounded-full bg-white text-blue-500">A</span>AIC</Link><nav className="mt-8 space-y-1">{NAV.map(([n,h,i],x)=><div key={h}>{(x===1||x===5)&&<p className="mb-2 mt-6 px-3 text-[10px] text-blue-100">{x===1?"ANALYZE":"RESEARCH"}</p>}<Link href={h} className={`flex gap-3 rounded-lg px-3 py-2.5 text-sm ${h==="/analysis-lab"?"bg-white/20 font-semibold":"hover:bg-white/10"}`}><span>{i}</span>{n}</Link></div>)}</nav></aside>
  <div className="min-w-0 flex-1 p-5 sm:p-8"><header className="flex justify-between gap-3"><div><h1 className="text-2xl font-bold">Automated Analysis Lab</h1><p className="mt-1 text-sm text-slate-500">Project: {selected?.name||"Select a research dataset"}</p></div><span className="h-fit rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-500">Private workspace</span></header>
   <ol className="mt-6 grid grid-cols-5 gap-2">{STEPS.map(([id,label],i)=><li key={id}><button disabled={i>index} onClick={()=>setStage(id)} className={`w-full border-t-2 pt-3 text-left text-xs sm:text-sm ${i===index?"border-blue-500 font-bold":i<index?"border-blue-300 text-slate-600":"border-slate-200 text-slate-400"}`}>{i+1}. {label}</button></li>)}</ol>
   {error&&<div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
   <div className="mt-7 grid gap-6 lg:grid-cols-[1fr_240px]"><section>
    {stage==="data"&&<><h2 className="text-xl font-bold">Choose your research data</h2><p className="mt-1 text-sm text-slate-500">Select an analysis-ready dataset from the authenticated workspace.</p><label className="mt-6 block text-sm font-medium">Dataset</label><select disabled={loading} value={datasetId} onChange={e=>setDatasetId(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"><option value="">{loading?"Loading datasets…":"Select a dataset…"}</option>{datasets.map(d=><option key={d.id} value={d.id}>{d.name}{d.country_iso3?` — ${d.country_iso3}`:""}{d.year?` (${d.year})`:""}</option>)}</select>{selected&&<div className="mt-5 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-4 text-sm"><p>Rows<strong className="block">{selected.row_count?.toLocaleString()||"Pending"}</strong></p><p>Variables<strong className="block">{selected.column_count||"Pending"}</strong></p><p>Country<strong className="block">{selected.country_iso3||"—"}</strong></p><p>Status<strong className="block capitalize">{selected.access_status}</strong></p></div>}<div className="mt-7 flex justify-end"><button disabled={!datasetId} onClick={()=>setStage("question")} className="rounded-lg bg-black px-5 py-2 text-sm font-semibold text-white disabled:opacity-40">Continue</button></div></>}
    {stage==="question"&&<><h2 className="text-xl font-bold">Ask your research question</h2><p className="mt-1 text-sm leading-6 text-slate-500">Describe the relationship you want to examine. AIC will not silently invent variables.</p><label className="mt-5 block text-sm">Research question</label><textarea value={question} onChange={e=>setQuestion(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border p-3 text-sm leading-6"/><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Outcome variable<input value={outcome} onChange={e=>setOutcome(e.target.value)} placeholder="e.g. crop_yield" className="mt-2 w-full rounded-xl border px-3 py-2"/></label><label className="text-sm">Research purpose<select value={purpose} onChange={e=>setPurpose(e.target.value as Purpose)} className="mt-2 w-full rounded-xl border bg-white px-3 py-2"><option value="association">Explanatory analysis</option><option value="prediction">Prediction</option><option value="causal">Causal inference</option></select></label></div><div className="mt-5 rounded-2xl border bg-slate-50 p-4"><h3 className="font-bold">AIC clarification</h3><p className="mt-1 text-sm leading-6 text-slate-600">Is your objective association, prediction, or a causal effect? Causal interpretation requires additional assumptions.</p><div className="mt-3 flex gap-2">{(["association","prediction","causal"] as Purpose[]).map(x=><button key={x} onClick={()=>setPurpose(x)} className={`rounded-lg px-3 py-2 text-sm capitalize ${purpose===x?"bg-black text-white":"border bg-white"}`}>{x==="causal"?"Causal effect":x}</button>)}</div></div><div className="mt-7 flex justify-between"><button onClick={()=>setStage("data")} className="rounded-lg border px-4 py-2 text-sm">Back</button><button disabled={busy} onClick={makePlan} className="rounded-lg bg-black px-5 py-2 text-sm font-semibold text-white">{busy?"Planning…":"Continue"}</button></div></>}
    {stage==="plan"&&plan&&<><h2 className="text-xl font-bold">Review the analysis plan</h2><p className="mt-2 text-sm leading-6 text-slate-600">{plan.rationale}</p><dl className="mt-5 divide-y rounded-xl border text-sm"><div className="flex justify-between p-4"><dt>Method</dt><dd className="font-bold">{plan.analysis_label}</dd></div><div className="flex justify-between p-4"><dt>Engine</dt><dd className="font-bold uppercase">{plan.engine}</dd></div><div className="flex justify-between p-4"><dt>Cleaning steps</dt><dd className="font-bold">{plan.cleaning_steps.length}</dd></div></dl>{Object.keys(params).length>0&&<div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.keys(params).map(k=><label key={k} className="text-xs capitalize">{k.replace(/_/g," ")}<input value={params[k]} onChange={e=>setParams({...params,[k]:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label>)}</div>}{purpose==="causal"&&<p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Causal interpretation requires a defensible identification design and assumptions.</p>}<label className="mt-5 flex gap-3 text-sm"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/><span><strong className="block">I reviewed and approve this plan</strong>Execution requires explicit approval.</span></label><div className="mt-7 flex justify-between"><button onClick={()=>setStage("question")} className="rounded-lg border px-4 py-2 text-sm">Back</button><button disabled={!approved||busy} onClick={run} className="rounded-lg bg-black px-5 py-2 text-sm font-semibold text-white disabled:opacity-40">Approve and execute</button></div></>}
    {stage==="execute"&&<div className="py-20 text-center"><div className="mx-auto grid h-16 w-16 animate-pulse place-items-center rounded-full bg-blue-100 text-2xl text-blue-600">✦</div><h2 className="mt-5 text-xl font-bold">Running approved analysis</h2><p className="mt-2 text-sm text-slate-500">Validating data, applying approved cleaning and generating diagnostics.</p></div>}
    {stage==="results"&&result&&<><p className="text-xs font-bold uppercase text-emerald-600">Analysis complete</p><h2 className="mt-1 text-xl font-bold">{plan?.analysis_label}</h2><article className="mt-5 rounded-xl border p-5"><h3 className="font-bold">Evidence summary</h3><p className="mt-3 whitespace-pre-line text-sm leading-7">{result.interpretation_text||"Analysis completed successfully. Review the full statistical output before reporting."}</p></article><div className="mt-7 flex justify-between"><button onClick={()=>setStage("plan")} className="rounded-lg border px-4 py-2 text-sm">Refine</button><button onClick={download} className="rounded-lg bg-black px-5 py-2 text-sm font-semibold text-white">Download record</button></div></>}
   </section><aside className="rounded-2xl border bg-slate-50 p-5"><h2 className="text-lg font-bold">Analysis record</h2><ul className="mt-4 space-y-3 text-sm"><li>◉ {selected?"Private dataset selected":"Dataset pending"}</li><li>◉ Identifiers checked</li><li>◉ Plan requires approval</li></ul><dl className="mt-5 divide-y border-y text-sm"><div className="flex justify-between py-3"><dt>Engine</dt><dd className="font-bold">{plan?.engine||"Pending"}</dd></div><div className="flex justify-between py-3"><dt>Model</dt><dd className="max-w-28 text-right font-bold">{plan?.analysis_label||"Pending"}</dd></div><div className="flex justify-between py-3"><dt>Code</dt><dd className="font-bold">{result?"Generated":"Not generated"}</dd></div><div className="flex justify-between py-3"><dt>Report</dt><dd className="font-bold">{result?"Available":"Not available"}</dd></div></dl><p className="mt-3 text-xs leading-5 text-slate-500">The reproducibility record stores data version, code, packages, model settings and execution time.</p></aside></div>
  </div></div></main>
}