"""
Static connector registry — source metadata for all 20 AIC data sources.

Each entry matches the DataSource model schema exactly. This dict is the
single source of truth for connector metadata; the DB is seeded from it.
Keys correspond to source_id values.
"""

from typing import TypedDict, Literal

ConnectorStatus = Literal["live", "planned", "user_upload", "deprecated"]
LicenseCategory = Literal["A", "B", "C", "D"]


class SourceMeta(TypedDict):
    source_id: str
    source_name: str
    source_type: str
    access_method: str
    license_category: LicenseCategory
    update_frequency: str
    requires_approval: bool
    redistribution_allowed: bool
    citation_required: bool
    data_owner: str
    connector_status: ConnectorStatus


REGISTRY: dict[str, SourceMeta] = {
    "world_bank": {
        "source_id": "world_bank",
        "source_name": "World Bank Open Data",
        "source_type": "Macroeconomic indicators, development statistics",
        "access_method": "REST API — api.worldbank.org/v2/",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "World Bank Group",
        "connector_status": "live",
    },
    "imf_api": {
        "source_id": "imf_api",
        "source_name": "IMF Data — JSON REST API",
        "source_type": "Macroeconomic indicators (WEO, IFS, DOTS, BOP)",
        "access_method": "REST API — dataservices.imf.org/IMF.Rest/DataService/",
        "license_category": "A",
        "update_frequency": "semi-annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "International Monetary Fund",
        "connector_status": "planned",
    },
    "un_sdg": {
        "source_id": "un_sdg",
        "source_name": "UN SDG Indicators Global Database",
        "source_type": "Sustainable Development Goal progress indicators",
        "access_method": "REST API — unstats.un.org/SDGAPI/v1/",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "United Nations Statistics Division",
        "connector_status": "planned",
    },
    "climate_chirps": {
        "source_id": "climate_chirps",
        "source_name": "CHIRPS Rainfall Estimates",
        "source_type": "Precipitation rasters — annual and seasonal rainfall by country",
        "access_method": "ClimateSERV API — climateserv.servirglobal.net (async job-based)",
        "license_category": "A",
        "update_frequency": "monthly",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "UCSB Climate Hazards Center (CHC)",
        "connector_status": "planned",
    },
    "nighttime_lights": {
        "source_id": "nighttime_lights",
        "source_name": "VIIRS Day/Night Band (NASA Black Marble)",
        "source_type": "Radiance rasters proxying economic activity",
        "access_method": "NASA Earthdata REST API — ladsweb.modaps.eosdis.nasa.gov",
        "license_category": "A",
        "update_frequency": "monthly",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "NASA / NOAA",
        "connector_status": "planned",
    },
    "commodity_prices_imf": {
        "source_id": "commodity_prices_imf",
        "source_name": "IMF Primary Commodity Prices",
        "source_type": "Global commodity prices (oil, metals, food, agriculture)",
        "access_method": "REST API — dataservices.imf.org/IMF.Rest/DataService/ (PCPS database)",
        "license_category": "A",
        "update_frequency": "monthly",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "International Monetary Fund",
        "connector_status": "planned",
    },
    "faostat": {
        "source_id": "faostat",
        "source_name": "FAOSTAT",
        "source_type": "Food and agriculture statistics",
        "access_method": "REST API — fenixservices.fao.org/faostat/api/v1/",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Food and Agriculture Organization of the UN",
        "connector_status": "live",
    },
    "who": {
        "source_id": "who",
        "source_name": "WHO Global Health Observatory",
        "source_type": "Health indicators for all countries",
        "access_method": "OData REST API — ghoapi.azureedge.net/api/",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "World Health Organization",
        "connector_status": "live",
    },
    "unesco_uis": {
        "source_id": "unesco_uis",
        "source_name": "UNESCO Institute for Statistics",
        "source_type": "Education indicators",
        "access_method": "SDMX REST API — api.uis.unesco.org/sdmx/v2/",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "UNESCO Institute for Statistics",
        "connector_status": "live",
    },
    "un_comtrade": {
        "source_id": "un_comtrade",
        "source_name": "UN Comtrade",
        "source_type": "International merchandise trade statistics",
        "access_method": "REST API — comtradeapi.un.org/public/v1/",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "United Nations Statistics Division",
        "connector_status": "live",
    },
    "wto": {
        "source_id": "wto",
        "source_name": "WTO Statistics",
        "source_type": "Trade in goods, services, and tariff data",
        "access_method": "REST API — api.wto.org/timeseries/v1/",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "World Trade Organization",
        "connector_status": "live",
    },
    "afdb": {
        "source_id": "afdb",
        "source_name": "African Development Bank Data Portal",
        "source_type": "African socioeconomic statistics, infrastructure, finance",
        "access_method": "Bulk CSV/XLSX download — dataportal.afdb.org",
        "license_category": "B",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "African Development Bank Group",
        "connector_status": "planned",
    },
    "rwanda_nisr": {
        "source_id": "rwanda_nisr",
        "source_name": "Rwanda National Institute of Statistics",
        "source_type": "National accounts, labour, trade, poverty, demographic statistics",
        "access_method": "File download — statistics.gov.rw",
        "license_category": "B",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Government of Rwanda / NISR",
        "connector_status": "planned",
    },
    "nigeria_nbs": {
        "source_id": "nigeria_nbs",
        "source_name": "Nigeria National Bureau of Statistics",
        "source_type": "CPI, GDP, trade, labour, poverty statistics",
        "access_method": "File download — nigerianstat.gov.ng",
        "license_category": "B",
        "update_frequency": "quarterly",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Government of Nigeria / NBS",
        "connector_status": "planned",
    },
    "afrobarometer_public": {
        "source_id": "afrobarometer_public",
        "source_name": "Afrobarometer",
        "source_type": "Pan-African survey — democracy, governance, trust, and quality-of-life indicators",
        "access_method": "REST API — api.afrobarometer.org/api/v2/ (public; 401/403 when auth required)",
        "license_category": "A",
        "update_frequency": "irregular",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Afrobarometer Network",
        "connector_status": "planned",
    },
    "procurement_ocds": {
        "source_id": "procurement_ocds",
        "source_name": "African Public Procurement Portals (OCDS)",
        "source_type": "Tender notices, awards, contract values",
        "access_method": "REST API or bulk JSON (Open Contracting Data Standard format)",
        "license_category": "B",
        "update_frequency": "weekly",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Individual government procurement agencies",
        "connector_status": "planned",
    },
    "ilo_ilostat": {
        "source_id": "ilo_ilostat",
        "source_name": "ILO ILOSTAT Database",
        "source_type": "Employment, unemployment, labour force participation by country",
        "access_method": "REST API or bulk CSV — ilostat.ilo.org/resources/SDMX-JSON-service/",
        "license_category": "B",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "International Labour Organization",
        "connector_status": "planned",
    },
    "enterprise_surveys": {
        "source_id": "enterprise_surveys",
        "source_name": "World Bank Enterprise Surveys",
        "source_type": "Firm-level business environment indicators (aggregated country profiles)",
        "access_method": "Bulk CSV/API download — enterprisesurveys.worldbank.org",
        "license_category": "B",
        "update_frequency": "per_survey_cycle",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "World Bank Group",
        "connector_status": "planned",
    },
    "commodity_prices_wb": {
        "source_id": "commodity_prices_wb",
        "source_name": "World Bank Commodity Price Data (Pink Sheet)",
        "source_type": "Monthly historical commodity prices (energy, metals, food, agriculture)",
        "access_method": "Excel file download — World Bank data site",
        "license_category": "B",
        "update_frequency": "monthly",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "World Bank Group",
        "connector_status": "planned",
    },
    "dhs_program": {
        "source_id": "dhs_program",
        "source_name": "DHS Program Microdata",
        "source_type": "Household health, nutrition, fertility, mortality survey microdata",
        "access_method": "User registers at dhsprogram.com and downloads approved datasets",
        "license_category": "C",
        "update_frequency": "per_survey_round",
        "requires_approval": True,
        "redistribution_allowed": False,
        "citation_required": True,
        "data_owner": "ICF International / USAID-funded DHS Program",
        "connector_status": "user_upload",
    },
    "unps_lsms": {
        "source_id": "unps_lsms",
        "source_name": "Uganda National Panel Survey (World Bank LSMS)",
        "source_type": "Longitudinal household welfare, agriculture, consumption panel data",
        "access_method": "World Bank Microdata Catalog — user registers and applies",
        "license_category": "C",
        "update_frequency": "biennial",
        "requires_approval": True,
        "redistribution_allowed": False,
        "citation_required": True,
        "data_owner": "Uganda Bureau of Statistics / World Bank",
        "connector_status": "user_upload",
    },
    "wb_microdata": {
        "source_id": "wb_microdata",
        "source_name": "World Bank Microdata Library",
        "source_type": "Household surveys, living standards measurement studies",
        "access_method": "microdata.worldbank.org — survey-specific access; some open, most licensed",
        "license_category": "C",
        "update_frequency": "per_survey",
        "requires_approval": True,
        "redistribution_allowed": False,
        "citation_required": True,
        "data_owner": "World Bank Group",
        "connector_status": "user_upload",
    },
    "ipums": {
        "source_id": "ipums",
        "source_name": "IPUMS International Census Microdata",
        "source_type": "Harmonised census and survey microdata for African countries",
        "access_method": "ipums.org — free registration; data use agreement per project",
        "license_category": "C",
        "update_frequency": "per_census_round",
        "requires_approval": True,
        "redistribution_allowed": False,
        "citation_required": True,
        "data_owner": "University of Minnesota / IPUMS",
        "connector_status": "user_upload",
    },
    "afrobarometer_licensed": {
        "source_id": "afrobarometer_licensed",
        "source_name": "Afrobarometer Licensed Microdata",
        "source_type": "Individual-level survey responses on governance, economy, society",
        "access_method": "Apply at afrobarometer.org/data/ — licensed access for researchers",
        "license_category": "C",
        "update_frequency": "per_round",
        "requires_approval": True,
        "redistribution_allowed": False,
        "citation_required": True,
        "data_owner": "Afrobarometer Network",
        "connector_status": "user_upload",
    },
    "ubos": {
        "source_id": "ubos",
        "source_name": "Uganda Bureau of Statistics",
        "source_type": "Population, economic, and social statistics for Uganda",
        "access_method": "CKAN OpenData portal — opendata.ubos.org",
        "license_category": "B",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Government of Uganda / UBOS",
        "connector_status": "planned",
    },
    "knbs": {
        "source_id": "knbs",
        "source_name": "Kenya National Bureau of Statistics",
        "source_type": "GDP, CPI, labour, poverty, demographic statistics for Kenya",
        "access_method": "CKAN OpenData portal — opendata.knbs.or.ke",
        "license_category": "B",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Government of Kenya / KNBS",
        "connector_status": "planned",
    },
    "nbs_tanzania": {
        "source_id": "nbs_tanzania",
        "source_name": "Tanzania National Bureau of Statistics",
        "source_type": "National accounts, trade, labour, demographic statistics for Tanzania",
        "access_method": "CKAN OpenData portal — opendata.nbs.go.tz",
        "license_category": "B",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Government of Tanzania / NBS",
        "connector_status": "planned",
    },
    "stats_south_africa": {
        "source_id": "stats_south_africa",
        "source_name": "Statistics South Africa",
        "source_type": "CPI, GDP, QLFS, poverty, census statistics for South Africa",
        "access_method": "SuperWEB2 portal + publications — statssa.gov.za",
        "license_category": "B",
        "update_frequency": "quarterly",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Government of South Africa / StatsSA",
        "connector_status": "planned",
    },
    "kobotoolbox_client": {
        "source_id": "kobotoolbox_client",
        "source_name": "Client KoboToolbox / ODK Survey Data",
        "source_type": "Custom field surveys, M&E data, program monitoring data",
        "access_method": "Client exports from own KoboToolbox/ODK account and uploads to AIC",
        "license_category": "D",
        "update_frequency": "on_demand",
        "requires_approval": False,
        "redistribution_allowed": False,
        "citation_required": False,
        "data_owner": "AIC client organisation",
        "connector_status": "live",
    },
    # ── Tier 3 ────────────────────────────────────────────────────────────────
    "ophi_mpi": {
        "source_id": "ophi_mpi",
        "source_name": "OPHI Global MPI",
        "source_type": "Multidimensional poverty headcount, intensity, and MPI scores",
        "access_method": "Bulk download — ophi.org.uk/global-mpi/",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Oxford Poverty and Human Development Initiative",
        "connector_status": "planned",
    },
    "owid": {
        "source_id": "owid",
        "source_name": "Our World in Data",
        "source_type": "Long-run development indicators (GDP, health, education, energy, environment)",
        "access_method": "CSV download via ourworldindata.org/grapher/",
        "license_category": "A",
        "update_frequency": "irregular",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Our World in Data / University of Oxford",
        "connector_status": "planned",
    },
    "polity5": {
        "source_id": "polity5",
        "source_name": "Polity5",
        "source_type": "Regime characteristics, democracy/autocracy scores",
        "access_method": "Bulk Excel/CSV download — systemicpeace.org/inscrdata.html",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Center for Systemic Peace",
        "connector_status": "planned",
    },
    "pts": {
        "source_id": "pts",
        "source_name": "Political Terror Scale",
        "source_type": "Political violence and human rights abuses (1-5 scale)",
        "access_method": "REST API — politicalterrorscale.org/api/",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Political Terror Scale project",
        "connector_status": "planned",
    },
    "vdem": {
        "source_id": "vdem",
        "source_name": "Varieties of Democracy (V-Dem)",
        "source_type": "Democracy indices, civil liberties, political corruption",
        "access_method": "REST API — api.vdemdata.com/v1/",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "V-Dem Institute, University of Gothenburg",
        "connector_status": "planned",
    },
    "acled": {
        "source_id": "acled",
        "source_name": "ACLED",
        "source_type": "Armed conflict events and fatalities (disaggregated location and actor)",
        "access_method": "REST API — api.acleddata.com (API key required)",
        "license_category": "B",
        "update_frequency": "weekly",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Armed Conflict Location & Event Data Project",
        "connector_status": "planned",
    },
    "aiddata": {
        "source_id": "aiddata",
        "source_name": "AidData",
        "source_type": "Geocoded development finance and aid flows from bilateral and multilateral donors",
        "access_method": "REST API or bulk download — aiddata.org / api.aiddata.org",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "AidData Research Lab, William & Mary",
        "connector_status": "planned",
    },
    "global_carbon_project": {
        "source_id": "global_carbon_project",
        "source_name": "Global Carbon Project",
        "source_type": "National fossil CO₂ emissions and carbon budget components",
        "access_method": "CSV download via Zenodo — zenodo.org",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "Global Carbon Project",
        "connector_status": "planned",
    },
    "climate_watch": {
        "source_id": "climate_watch",
        "source_name": "Climate Watch",
        "source_type": "GHG emissions (CAIT), NDC targets, climate policy data",
        "access_method": "REST API — climatewatchdata.org/api/v1/",
        "license_category": "A",
        "update_frequency": "annual",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "World Resources Institute",
        "connector_status": "planned",
    },
    "nasa_power": {
        "source_id": "nasa_power",
        "source_name": "NASA POWER",
        "source_type": "Surface meteorology and solar energy climatology (temperature, precipitation, solar)",
        "access_method": "REST API — power.larc.nasa.gov/api/",
        "license_category": "A",
        "update_frequency": "monthly",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "NASA Langley Research Center",
        "connector_status": "live",
    },
    "era5": {
        "source_id": "era5",
        "source_name": "ERA5",
        "source_type": "ECMWF reanalysis — atmospheric, land surface, and oceanic climate variables",
        "access_method": "Copernicus CDS API — cds.climate.copernicus.eu (free registration)",
        "license_category": "A",
        "update_frequency": "monthly",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "European Centre for Medium-Range Weather Forecasts (ECMWF)",
        "connector_status": "planned",
    },
    "osm": {
        "source_id": "osm",
        "source_name": "OpenStreetMap",
        "source_type": "Infrastructure features (hospitals, schools, roads) by country",
        "access_method": "Overpass API — overpass-api.de",
        "license_category": "A",
        "update_frequency": "weekly",
        "requires_approval": False,
        "redistribution_allowed": True,
        "citation_required": True,
        "data_owner": "OpenStreetMap contributors (ODbL)",
        "connector_status": "live",
    },
}


def get_source(source_id: str) -> SourceMeta:
    """Return registry entry by source_id; raises KeyError if not found."""
    return REGISTRY[source_id]


def list_sources(
    license_category: str | None = None,
    connector_status: str | None = None,
) -> list[SourceMeta]:
    """Return all sources, optionally filtered by category or status."""
    sources = list(REGISTRY.values())
    if license_category:
        sources = [s for s in sources if s["license_category"] == license_category]
    if connector_status:
        sources = [s for s in sources if s["connector_status"] == connector_status]
    return sources
