"use client";

import { useState } from "react";
import {
  fetchSeriesInsight,
  type InsightResponse,
  type InsightSeriesInput,
} from "@/lib/api";

type Action = "interpret" | "explain" | "recommend" | "compare";

export default function AIInsightPanel({
  title,
  metric,
  series,
}: {
  title: string;
  metric: string;
  series: InsightSeriesInput[];
}) {
  const [loading, setLoading] = useState<Action | null>(null);
  const [result, setResult] = useState<InsightResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function run(action: Action) {
    if (!series.length) return;
    setLoading(action);
    setError(null);
    try {
      const res = await fetchSeriesInsight({ action, title, metric, series });
      setResult(res);
    } catch {
      setError("The insight service is warming up — please try again in a moment.");
    } finally {
      setLoading(null);
    }
  }

  function downloadBrief() {
    if (!result) return;
    const lines = [
      `# Policy Brief — ${title}`,
      "",
      "## AI interpretation",
      result.insight,
      "",
    ];
    if (result.stats?.length) {
      lines.push("## Key figures");
      for (const s of result.stats) {
        lines.push(
          `- ${s.label}: ${s.start_value} ${s.units} (${s.start_year}) → ${s.end_value} (${s.end_year}), ` +
            `${s.pct_change ?? "?"}% total${s.cagr_pct != null ? `, ${s.cagr_pct}%/yr` : ""}; ` +
            `peak ${s.peak_value} in ${s.peak_year}, low ${s.trough_value} in ${s.trough_year}.`
        );
      }
      lines.push("");
    }
    if (result.recommendations?.length) {
      lines.push("## Suggested interventions (AI-generated, validate before acting)");
      result.recommendations.forEach((r) => lines.push(`- ${r}`));
      lines.push("");
    }
    lines.push(`_Generated by AIC Intelligence. Figures are computed from the plotted data; interpretations are AI-assisted._`);
    const blob = new Blob([lines.join("\n")], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "aic_policy_brief.md";
    a.click();
    URL.revokeObjectURL(url);
  }

  const btn =
    "text-sm font-medium rounded-lg px-3 py-2 border border-aic-green text-aic-green hover:bg-aic-green hover:text-white transition disabled:opacity-50";

  return (
    <section className="bg-gradient-to-br from-emerald-50 to-white rounded-xl p-6 border border-emerald-100 mt-8">
      <div className="flex items-center gap-2 mb-3">
        <span className="inline-flex items-center justify-center w-7 h-7 rounded-full bg-aic-green text-white text-sm font-bold">
          AI
        </span>
        <h3 className="text-lg font-semibold text-aic-dark">AIC AI Insight</h3>
        {result?.source && (
          <span className="text-xs text-aic-muted ml-auto">
            {result.source === "llm" ? "Gemini-assisted" : result.source === "heuristic" ? "rule-based" : result.source}
          </span>
        )}
      </div>

      {!result && !loading && (
        <p className="text-aic-muted text-sm mb-4">
          Generate a plain-language reading of the chart above — figures are computed directly from the data,
          interpretation is AI-assisted and never invents causes.
        </p>
      )}

      {loading && <p className="text-aic-muted text-sm mb-4">Analysing…</p>}
      {error && <p className="text-aic-red text-sm mb-4">{error}</p>}

      {result && (
        <div className="mb-5">
          <p className="text-aic-dark leading-relaxed whitespace-pre-line">{result.insight}</p>

          {result.recommendations?.length > 0 && (
            <ul className="mt-4 space-y-1.5 list-disc pl-5 text-sm text-aic-dark">
              {result.recommendations.map((r, i) => (
                <li key={i}>{r}</li>
              ))}
            </ul>
          )}

          {result.action === "compare" && result.peers && (
            <div className="mt-4 text-sm">
              {Object.keys(result.peers).length === 0 && (
                <p className="text-aic-muted">Add more countries in the explorer to compare directly.</p>
              )}
              {Object.entries(result.peers).map(([crop, list]) => (
                <p key={crop} className="text-aic-dark">
                  <span className="font-semibold">{crop}</span> is also grown by:{" "}
                  <span className="text-aic-muted">{list.join(", ")}</span>
                </p>
              ))}
            </div>
          )}
        </div>
      )}

      <div className="flex flex-wrap gap-2">
        <button type="button" className={btn} disabled={loading !== null} onClick={() => run("interpret")}>
          {loading === "interpret" ? "…" : "Explain Results"}
        </button>
        <button type="button" className={btn} disabled={loading !== null} onClick={() => run("recommend")}>
          {loading === "recommend" ? "…" : "Recommend Interventions"}
        </button>
        <button type="button" className={btn} disabled={loading !== null} onClick={() => run("compare")}>
          {loading === "compare" ? "…" : "Compare with Similar Countries"}
        </button>
        <button
          type="button"
          className="text-sm font-medium rounded-lg px-3 py-2 bg-aic-green text-white hover:bg-emerald-700 transition disabled:opacity-50"
          disabled={!result}
          onClick={downloadBrief}
          title={result ? "Download a Markdown policy brief" : "Run an insight first"}
        >
          Generate Policy Brief
        </button>
      </div>
    </section>
  );
}
